name: tdd_clean_architecture
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  flutter_bloc: ^8.1.3
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  connectivity_plus: ^5.0.1
  shared_preferences: ^2.2.2
  internet_connection_checker: ^1.0.0+1
  http: ^1.1.0
  neumorphic_button: ^0.0.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

